version: "3.9"

services:
  # Laravel (Backend)
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: trello_app
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    networks:
      - trello_network
  # Nginx server
  nginx:
    image: nginx:latest
    container_name: trello_nginx
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - trello_network
