version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: datasynchub-app
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        depends_on:
            - postgres
            - mysql
            - mongo
        command: php artisan serve --host=0.0.0.0 --port=8000
        networks:
            - app-network

    postgres:
        image: postgres:16
        container_name: datasynchub-postgres
        environment:
            POSTGRES_DB: datasynchub
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - app-network

    mysql:
        image: mysql:8.0
        container_name: datasynchub-mysql
        environment:
            MYSQL_DATABASE: datasynchub
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: rootpassword
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - app-network

    mongo:
        image: mongo:7.0
        container_name: datasynchub-mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: user
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: datasynchub
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: datasynchub-phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_USER: user
            PMA_PASSWORD: password
            PMA_ARBITRARY: 1
        ports:
            - "8080:80"
        depends_on:
            - mysql
        networks:
            - app-network

    pgadmin:
        image: dpage/pgadmin4
        container_name: datasynchub-pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "5050:80"
        depends_on:
            - postgres
        networks:
            - app-network

    mongoexpress:
        image: mongo-express
        container_name: datasynchub-mongoexpress
        environment:
            ME_CONFIG_MONGODB_SERVER: mongo
            ME_CONFIG_MONGODB_ADMINUSERNAME: user
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
            ME_CONFIG_BASICAUTH_USERNAME: admin
            ME_CONFIG_BASICAUTH_PASSWORD: admin
        ports:
            - "8081:8081"
        depends_on:
            - mongo
        networks:
            - app-network

volumes:
    postgres_data:
    mysql_data:
    mongo_data:

networks:
    app-network:
        driver: bridge
