version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: datasynchub-app
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        depends_on:
            - postgres
            - mysql
            - mongo
        command: php artisan serve --host=0.0.0.0 --port=8000
        networks:
            - app-network

    postgres:
        image: postgres:16
        container_name: datasynchub-postgres
        environment:
            POSTGRES_DB: datasynchub
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - app-network

    mysql:
        image: mysql:8.0
        container_name: datasynchub-mysql
        environment:
            MYSQL_DATABASE: datasynchub
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: rootpassword
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - app-network
